info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2022-12-21T03:02:12.278Z"}
info: Connected to the database. {"timestamp":"2022-12-21T03:02:15.376Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee3$ (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\src\services\/user.service.js:21:13)
    at tryCatch (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/loginuser 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-21T03:02:26.133Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2022-12-21T03:02:45.694Z"}
info: Connected to the database. {"timestamp":"2022-12-21T03:03:00.762Z"}
error: 
    status - 500 
    message - Error: Invalid user
    at _callee3$ (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\src\services\/user.service.js:27:11)
    at tryCatch (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/loginuser 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-21T03:03:10.711Z"}
error: 
    status - 500 
    message - Error: Invalid user
    at _callee3$ (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\src\services\/user.service.js:27:11)
    at tryCatch (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/loginuser 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-21T03:09:38.717Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2022-12-21T04:40:05.692Z"}
info: Connected to the database. {"timestamp":"2022-12-21T04:40:08.597Z"}
error: 
    status - 500 
    message - Error: Invalid  email
    at _callee3$ (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\src\services\/user.service.js:36:11)
    at tryCatch (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/loginuser 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-21T04:40:23.607Z"}
error: 
    status - 500 
    message - Error: Password is invalid
    at _callee3$ (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\src\services\/user.service.js:33:13)
    at tryCatch (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/loginuser 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-21T04:40:44.292Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-21T04:47:27.237Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2022-12-21T04:48:24.392Z"}
info: Connected to the database. {"timestamp":"2022-12-21T04:48:27.248Z"}
error: 
    status - 500 
    message - Error: User with same mailid Already exits
    at _callee2$ (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\src\services\/user.service.js:13:11)
    at tryCatch (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-21T04:48:36.726Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2022-12-21T04:49:03.188Z"}
info: Connected to the database. {"timestamp":"2022-12-21T04:49:05.693Z"}
error: 
    status - 500 
    message - Error: User with same mailid Already exits
    at _callee2$ (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\src\services\/user.service.js:13:11)
    at tryCatch (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Gajanan\OneDrive\Desktop\BasicsJS\Fundo-note\Fundo-note\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-12-21T04:50:35.884Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2022-12-21T04:56:24.363Z"}
info: Connected to the database. {"timestamp":"2022-12-21T04:56:26.868Z"}
